(add-to-list 'exec-path-from-shell-variables "ALTERNATE_EDITOR")
(add-to-list 'exec-path-from-shell-variables "EDITOR")
(add-to-list 'exec-path-from-shell-variables "GPG_AGENT_INFO")
(add-to-list 'exec-path-from-shell-variables "INFOPATH")
(add-to-list 'exec-path-from-shell-variables "SSH_AUTH_SOCK")
